name: Blender Animation
on: workflow_dispatch
jobs:
  render:
    runs-on: ubuntu-latest
    container: nytimes/rd-blender-docker:latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Script
        run: echo "${{ secrets.MY_BPY_SCRIPT }}" > scene.py
      - name: Run Blender Render
        run: |
          blender -b -P scene.py --python-expr "import bpy; bpy.context.scene.render.filepath='//output.mp4'; bpy.ops.render.render(animation=True)"
      - uses: actions/upload-artifact@v4
        with:
          name: video-file
          path: output.mp4
          retention-days: 1
